# Generated by Django 3.1.4 on 2021-01-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210102_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='images',
            new_name='image',
        ),
    ]
